### ISSUE TITLE
No link to the paper 

### ISSUE THREAD

**Issue by vrushti1991** [SoftwareEngineeringToolDemos/FSE-2011-Synoptic#2]

**Comment by PriyadarshiniRajagopal** [comment]
There is a link to the original IEEE paper in the README file. Is there anything more?

**Comment by vrushti1991** [comment]
Sorry if I missed it. I will close it

**Comment by vrushti1991** [comment]
Found and closed it. Sorry about that.

**Comment by PriyadarshiniRajagopal** [comment]
Issue was opened by mistake.
