### ISSUE TITLE
Error in running the eample command

### ISSUE THREAD

**Issue by vrushti1991** [SoftwareEngineeringToolDemos/FSE-2011-Synoptic#8]
On running the osx login command it says that 
./traces/abstract/osx-login-example/trace-full.txt does not exist

**Comment by PriyadarshiniRajagopal** [comment]
That's because it's a trace-full.log file. I should have mentioned that. I'll change the README on the VM accordingly.

**Comment by PriyadarshiniRajagopal** [comment]
Fixed and change viewable in the next ova export.
